import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "inverse-primary": "#b0c9e8",
        "on-tertiary-container": "#00a270",
        "background": "#f8f9ff",
        "outline-variant": "#c3c6ce",
        "on-primary": "#ffffff",
        "tertiary-container": "#002e1d",
        "inverse-surface": "#213145",
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#00170c",
        "on-background": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "error-container": "#ffdad6",
        "surface-tint": "#49607c",
        "outline": "#74777e",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#314863",
        "primary-container": "#0f2942",
        "surface-container-high": "#dce9ff",
        "primary-fixed": "#d1e4ff",
        "on-tertiary-fixed-variant": "#005236",
        "primary": "#001428",
        "secondary-container": "#316bf3",
        "on-primary-fixed": "#011d35",
        "tertiary-fixed-dim": "#4edea3",
        "on-surface": "#0b1c30",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#b0c9e8",
        "on-secondary-container": "#fefcff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#7991af",
        "on-tertiary-fixed": "#002113",
        "surface": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed": "#dbe1ff",
        "on-secondary-fixed": "#00174b",
        "tertiary-fixed": "#6ffbbe",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "secondary": "#0051d5",
        "on-surface-variant": "#43474d",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#003ea8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xl": "2rem",
        "space-md": "1rem",
        gutter: "1.25rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        margin: "1.5rem",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", fontWeight: "600" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", fontWeight: "700" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        "headline-xl-mobile": ["1.5rem", { lineHeight: "2rem", fontWeight: "700" }],
        "headline-xl": ["2rem", { lineHeight: "2.5rem", fontWeight: "700" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
